### ISSUE TITLE
.travis.yml: The 'sudo' tag is now deprecated in Travis CI

### ISSUE THREAD

**Issue by cclauss** [IBM/reactive-components#10]
[Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).

"_If you currently specify __sudo: false__ in your __.travis.yml__, we recommend removing that configuration_"

**Comment by FcoJavierSainz** [comment]
Hi I am using different configuration `sudo: required`

Thank you

**Comment by cclauss** [comment]
The __sudo__ tags is a no-op.  In other words it is ___always___ enabled.

**Comment by FcoJavierSainz** [comment]
So, Do I need to remove it anyway?

**Comment by cclauss** [comment]
You should.

**Comment by FcoJavierSainz** [comment]
Done
